[package]
name = "sc3tools"
version = "2.0.0"
authors = ["Committee of Zero"]
edition = "2018"

[dependencies]
nom = "5.1"
rust-embed = "5.6"
hex = "0.4"
clap = "2.33"
lazy_static = "1.4"
glob = "0.3"
termcolor = "1.1"
itertools = "0.9"
byteorder = "1.3"